version: '3.8'

services:
  test-vnc:
    build: ./test-vnc-simple
    container_name: test-vnc-server
    ports:
      - "5900:5900"
    networks:
      - nop_nop-internal
    restart: unless-stopped

networks:
  nop_nop-internal:
    external: true
